# Generated by Django 4.2.22 on 2025-08-07 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 7, 10, 15, 31, 491152, tzinfo=datetime.timezone.utc)),
        ),
    ]
