# Generated by Django 4.2.22 on 2025-08-07 10:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 7, 10, 17, 35, 657812, tzinfo=datetime.timezone.utc)),
        ),
    ]
